import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Header from '@/components/layout/Header';  
import Footer from "@/components/layout/Footer";
import '@/styles/main.scss';
import { UserProvider } from "@/context/userProvider";
import Menu from "@/components/layout/Menu";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <UserProvider>
      <html lang="en">
        <body className={inter.className}>
          <Header />
          <Menu />
          {children}
          <Footer />
        </body>
      </html>
    </UserProvider>
  );  
};